import { CredentialItem, ActivityLogItem, EmergencyContact, BreachRecord } from '../types/vault';

export const INITIAL_MOCK_ACCOUNTS: CredentialItem[] = [
  {
    id: 'acc-github-1',
    serviceName: 'GitHub',
    websiteUrl: 'https://github.com',
    username: 'alexdev2026',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p1_k92Jshd8!93jKd81',
    iv: 'iv_mock_gh_128',
    category: 'Developer',
    tags: ['developer', 'code', 'deployments', 'important'],
    notes: 'Main personal developer account. Attached to production SSH keys.',
    createdAt: '2023-04-12T10:00:00.000Z',
    updatedAt: '2026-08-15T14:20:00.000Z',
    lastRotated: '2026-08-15T14:20:00.000Z',
    passwordStrength: 'Strong',
    strengthScore: 88,
    twoFactorStatus: 'Enabled',
    totpSecretEncrypted: 'JBSWY3DPEHPK3PXP', // Base32 test secret (RFC 3548 standard test secret)
    hasTotpConfigured: true,
    passkeyStatus: 'Available',
    recoveryStatus: 'Complete',
    recoveryEmail: 'alex.recovery@protonmail.com',
    isFavorite: true,
    isAbandoned: false,
  },
  {
    id: 'acc-openai-2',
    serviceName: 'OpenAI Platform',
    websiteUrl: 'https://platform.openai.com',
    username: 'alex.vanguard@gmail.com',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p2_u83jL92kM!x09',
    iv: 'iv_mock_oa_129',
    category: 'AI Tools',
    tags: ['ai', 'developer', 'api-keys', 'work'],
    notes: 'Holds credit card on file for GPT-4 API access.',
    createdAt: '2023-11-20T11:00:00.000Z',
    updatedAt: '2026-07-10T09:15:00.000Z',
    lastRotated: '2026-07-10T09:15:00.000Z',
    passwordStrength: 'Strong',
    strengthScore: 84,
    twoFactorStatus: 'Enabled',
    totpSecretEncrypted: 'HXDMVJECJJWSRB3H',
    hasTotpConfigured: true,
    passkeyStatus: 'Active',
    recoveryStatus: 'Complete',
    isFavorite: true,
  },
  {
    id: 'acc-linkedin-3',
    serviceName: 'LinkedIn',
    websiteUrl: 'https://linkedin.com',
    username: 'alex-vanguard-pro',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p3_reused_pass1',
    iv: 'iv_mock_li_130',
    category: 'Social',
    tags: ['career', 'social', 'networking'],
    notes: 'Password shared with Canva (needs immediate rotation).',
    createdAt: '2022-01-14T08:00:00.000Z',
    updatedAt: '2025-10-04T12:00:00.000Z',
    lastRotated: '2025-10-04T12:00:00.000Z', // 11 months old
    passwordStrength: 'Fair',
    strengthScore: 48,
    twoFactorStatus: 'Disabled',
    hasTotpConfigured: false,
    passkeyStatus: 'Not Supported',
    recoveryStatus: 'Incomplete',
    isFavorite: false,
  },
  {
    id: 'acc-canva-4',
    serviceName: 'Canva',
    websiteUrl: 'https://canva.com',
    username: 'alexdesign',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p3_reused_pass1', // Reused with LinkedIn
    iv: 'iv_mock_cv_131',
    category: 'Work',
    tags: ['design', 'presentations', 'marketing'],
    notes: 'Reused password from 2025.',
    createdAt: '2022-09-18T16:00:00.000Z',
    updatedAt: '2025-09-18T16:00:00.000Z',
    lastRotated: '2025-09-18T16:00:00.000Z',
    passwordStrength: 'Fair',
    strengthScore: 48,
    twoFactorStatus: 'Disabled',
    hasTotpConfigured: false,
    passkeyStatus: 'Not Supported',
    recoveryStatus: 'Missing',
    isFavorite: false,
  },
  {
    id: 'acc-vercel-5',
    serviceName: 'Vercel',
    websiteUrl: 'https://vercel.com',
    username: 'alexvanguard',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p5_v92Kms!892nL',
    iv: 'iv_mock_vc_132',
    category: 'Developer',
    tags: ['developer', 'hosting', 'production'],
    notes: 'Connected via GitHub OAuth & SSO.',
    createdAt: '2023-02-10T14:30:00.000Z',
    updatedAt: '2026-06-01T11:00:00.000Z',
    lastRotated: '2026-06-01T11:00:00.000Z',
    passwordStrength: 'Very Strong',
    strengthScore: 94,
    twoFactorStatus: 'Enabled',
    totpSecretEncrypted: 'GEZDGNBVGY3TQOJQ',
    hasTotpConfigured: true,
    passkeyStatus: 'Active',
    recoveryStatus: 'Complete',
    isFavorite: true,
  },
  {
    id: 'acc-aws-6',
    serviceName: 'AWS Console',
    websiteUrl: 'https://aws.amazon.com',
    username: 'root-admin-alex',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p6_Kw82!9sn3kL90',
    iv: 'iv_mock_aws_133',
    category: 'Developer',
    tags: ['cloud', 'infrastructure', 'critical'],
    notes: 'Root account with IAM governance.',
    createdAt: '2022-06-01T09:00:00.000Z',
    updatedAt: '2026-08-01T10:00:00.000Z',
    lastRotated: '2026-08-01T10:00:00.000Z',
    passwordStrength: 'Very Strong',
    strengthScore: 98,
    twoFactorStatus: 'Enabled',
    totpSecretEncrypted: 'MFRGGZDFMZTWQ2LK',
    hasTotpConfigured: true,
    passkeyStatus: 'Active',
    recoveryStatus: 'Complete',
    isFavorite: true,
  },
  {
    id: 'acc-stripe-7',
    serviceName: 'Stripe Dashboard',
    websiteUrl: 'https://dashboard.stripe.com',
    username: 'alex.finance@vanguard.io',
    email: 'alex.finance@vanguard.io',
    encryptedPassword: 'sv_enc_p7_strp82!k09sM',
    iv: 'iv_mock_str_134',
    category: 'Finance',
    tags: ['finance', 'payments', 'critical'],
    notes: 'Company payouts & customer billing.',
    createdAt: '2023-08-11T13:45:00.000Z',
    updatedAt: '2026-07-22T17:30:00.000Z',
    lastRotated: '2026-07-22T17:30:00.000Z',
    passwordStrength: 'Very Strong',
    strengthScore: 96,
    twoFactorStatus: 'Enabled',
    totpSecretEncrypted: 'ORUGKIDROVUWG2ZH',
    hasTotpConfigured: true,
    passkeyStatus: 'Active',
    recoveryStatus: 'Complete',
    isFavorite: true,
  },
  {
    id: 'acc-claude-8',
    serviceName: 'Anthropic Claude',
    websiteUrl: 'https://claude.ai',
    username: 'alex.vanguard@gmail.com',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p8_cld93k!89sK',
    iv: 'iv_mock_cld_135',
    category: 'AI Tools',
    tags: ['ai', 'research', 'work'],
    notes: 'Pro Claude subscription.',
    createdAt: '2024-03-01T10:00:00.000Z',
    updatedAt: '2026-08-10T12:10:00.000Z',
    lastRotated: '2026-08-10T12:10:00.000Z',
    passwordStrength: 'Strong',
    strengthScore: 86,
    twoFactorStatus: 'Enabled',
    hasTotpConfigured: false,
    passkeyStatus: 'Available',
    recoveryStatus: 'Complete',
  },
  {
    id: 'acc-coursera-9',
    serviceName: 'Coursera',
    websiteUrl: 'https://coursera.org',
    username: 'alexlearns',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p9_simplepass2024',
    iv: 'iv_mock_cou_136',
    category: 'Education',
    tags: ['education', 'college', 'certificates'],
    notes: 'Algorithms & AI specialization.',
    createdAt: '2022-04-10T11:00:00.000Z',
    updatedAt: '2024-08-15T10:00:00.000Z',
    lastRotated: '2024-08-15T10:00:00.000Z',
    passwordStrength: 'Weak',
    strengthScore: 32,
    twoFactorStatus: 'Disabled',
    hasTotpConfigured: false,
    passkeyStatus: 'Not Supported',
    recoveryStatus: 'Incomplete',
    isAbandoned: true, // Abandoned
  },
  {
    id: 'acc-notion-10',
    serviceName: 'Notion',
    websiteUrl: 'https://notion.so',
    username: 'alexvanguard',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p10_ntn93kLm!928',
    iv: 'iv_mock_ntn_137',
    category: 'Work',
    tags: ['work', 'notes', 'docs', 'project'],
    notes: 'Team workspace and architectural blueprints.',
    createdAt: '2023-01-05T09:00:00.000Z',
    updatedAt: '2026-08-20T15:00:00.000Z',
    lastRotated: '2026-08-20T15:00:00.000Z',
    passwordStrength: 'Strong',
    strengthScore: 82,
    twoFactorStatus: 'Enabled',
    totpSecretEncrypted: 'KRSXG5CTMVRXEZLU',
    hasTotpConfigured: true,
    passkeyStatus: 'Available',
    recoveryStatus: 'Complete',
  },
  {
    id: 'acc-oldforum-11',
    serviceName: 'Old Tech Forum',
    websiteUrl: 'https://techforum-archive.org',
    username: 'alex_99',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p11_oldforumPass',
    iv: 'iv_mock_otf_138',
    category: 'Personal',
    tags: ['temporary', 'forum', 'archive'],
    notes: 'Last accessed 14 months ago.',
    createdAt: '2021-02-14T09:00:00.000Z',
    updatedAt: '2023-05-10T10:00:00.000Z',
    lastRotated: '2023-05-10T10:00:00.000Z',
    passwordStrength: 'Weak',
    strengthScore: 28,
    twoFactorStatus: 'Disabled',
    hasTotpConfigured: false,
    passkeyStatus: 'Not Supported',
    recoveryStatus: 'Missing',
    isAbandoned: true,
  },
  {
    id: 'acc-figma-12',
    serviceName: 'Figma',
    websiteUrl: 'https://figma.com',
    username: 'alex.vanguard@gmail.com',
    email: 'alex.vanguard@gmail.com',
    encryptedPassword: 'sv_enc_p12_fgm9381!kS98',
    iv: 'iv_mock_fgm_139',
    category: 'Work',
    tags: ['design', 'ui', 'work', 'project'],
    notes: 'Client design systems and UI prototypes.',
    createdAt: '2023-05-12T14:00:00.000Z',
    updatedAt: '2026-07-28T16:20:00.000Z',
    lastRotated: '2026-07-28T16:20:00.000Z',
    passwordStrength: 'Strong',
    strengthScore: 85,
    twoFactorStatus: 'Enabled',
    hasTotpConfigured: false,
    passkeyStatus: 'Available',
    recoveryStatus: 'Complete',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLogItem[] = [
  {
    id: 'log-1',
    timestamp: '2026-09-04T10:42:00.000Z',
    actionType: 'SECURITY_AUDIT',
    title: 'AI Security Audit completed',
    details: 'Ecosystem scan completed. Identified 3 optimization items, Score: 87/100',
    ipAddress: '192.168.1.42',
    device: 'MacBook Pro — Chrome 128',
    status: 'success',
  },
  {
    id: 'log-2',
    timestamp: '2026-09-04T10:38:00.000Z',
    actionType: 'ACCOUNT_UPDATED',
    title: 'GitHub credential updated',
    details: 'Rotated password with 24-character cryptographic token.',
    ipAddress: '192.168.1.42',
    device: 'MacBook Pro — Chrome 128',
    status: 'success',
  },
  {
    id: 'log-3',
    timestamp: '2026-09-04T10:30:00.000Z',
    actionType: 'ACCOUNT_CREATED',
    title: 'New credential added: Stripe Dashboard',
    details: 'Added to Finance category with TOTP hardware authentication.',
    ipAddress: '192.168.1.42',
    device: 'MacBook Pro — Chrome 128',
    status: 'success',
  },
  {
    id: 'log-4',
    timestamp: '2026-09-04T09:15:00.000Z',
    actionType: 'LOGIN',
    title: 'Vault Unlocked via Master Key',
    details: 'Zero-knowledge client derivation in 184ms.',
    ipAddress: '192.168.1.42',
    device: 'MacBook Pro — Chrome 128',
    status: 'success',
  },
  {
    id: 'log-5',
    timestamp: '2026-09-03T18:22:00.000Z',
    actionType: 'PASSWORD_COPIED',
    title: 'AWS Console password copied to clipboard',
    details: 'Clipboard auto-cleared after 30 seconds.',
    ipAddress: '192.168.1.42',
    device: 'MacBook Pro — Chrome 128',
    status: 'warning',
  },
];

export const INITIAL_BREACH_RECORDS: BreachRecord[] = [
  {
    id: 'breach-1',
    serviceName: 'GraphicDesignMarket Archive',
    domain: 'graphicdesignmarket.io',
    breachDate: '2025-11-14',
    addedDate: '2026-01-10',
    pwnCount: 4200000,
    description: 'A third-party graphic resource platform suffered an unauthenticated database dump. Passwords were stored in legacy salted SHA-1.',
    exposedData: ['Email addresses', 'Usernames', 'Hashed passwords', 'IP addresses'],
    isVerified: true,
    recommendedAction: 'Rotate all credentials sharing email alex.vanguard@gmail.com on creative design sites.',
    status: 'active_threat',
  },
  {
    id: 'breach-2',
    serviceName: 'OldTechHub Forum',
    domain: 'oldtechhub.com',
    breachDate: '2024-03-08',
    addedDate: '2024-05-12',
    pwnCount: 1800000,
    description: 'Archived community forum dataset exposed via misconfigured cloud bucket.',
    exposedData: ['Email addresses', 'Forum handles'],
    isVerified: true,
    recommendedAction: 'No active passwords stored. Account reviewed and marked safe.',
    status: 'remediated',
  },
];

export const INITIAL_EMERGENCY_CONTACTS: EmergencyContact[] = [
  {
    id: 'ec-1',
    fullName: 'Elena Rostova',
    email: 'elena.rostova@protonmail.com',
    relationship: 'Partner / Trusted Contact',
    status: 'Active',
    waitingPeriodHours: 48,
    grantDate: '2026-01-15',
  },
];
